#+TITLE: Unit 1 Notes
#+AUTHOR: Ankur Mishra
#+DATE: 2/28/2018
* Columnar Transposition Ciphers
** Simple Columnar Transposition Cipher
General Process: Rearranging letters based on numeric key.\\
*** Encoding
To encode, put text in to a matrix, which has $c$ columns, where $c$ = key. 
Then copy each column from left to right to create your a new encoded message.
*** Decoding
To decode, first approximate the number of rows (r) by dividing the length of the decoded message by the key. 
Then write each letter of the encoded message from up to down, till the row length is reached. 
Keep in mind, if there is a reminder($x$) when calculating the number of rows, leave $x$ spaces blank in the last row.
*** Example
Text: "REARRANGING LETTERS" | Key: 5 \\
$18 / 5 = 4 R 2$
\begin{equation}
\begin{bmatrix}
    1 & 2 & 3 & 4 & 5 \\
    \\
    R & E & A & R & R \\
    A & N & G & I & N \\
    G & L & E & T & T \\
    E & R & S & _ & _ \\
\end{bmatrix}
\end{equation}
Encoded: RAGEENLRAGESRIT RNT 
** Keyword Columnar Transposition Cipher
General Process: Rearranging letters based on a keyword and each keyword letter's alphabetical order.
*** Encoding
To encode, put text in to a matrix, which has
$c$ columns, where $c$ = the length of the keyword. Keep each letter of your keyword above each column of the matrix.
Then copy each column from based on your keyword's alphabetical order to create your a new encoded message.\\ 
*** Decoding
To decode, first find the length of the ciphered text, then divide it by the length of the keyword, which will return the number of rows $r$.
If it has a remainder $x$, round the number of rows up and you will have $x$ blank spaces in the text. Fill each column out based on the alphabetial order of
the keyword and by copying every $r$ letters from the ciphered text into the column. Finally copy each row and you will get your plaintext back.
*** Example
Text: "SLIGHTLY MORE COMPLICATED" | Keyword: CRYPTO \\
\begin{equation}
\begin{bmatrix}
    C & R & Y & P & T & O \\
    \\
    S & L & I & G & H & T \\
    L & Y & M & O & R & E \\
    C & O & M & P & L & I \\
    C & A & T & E & D & _ \\
\end{bmatrix}
\end{equation}
Encoded: SLCCTEI GOPELYOAHRLDIMMT
* Playfair Cipher and Railfence Cipher
** Playfair Cipher
*** Encoding
To encode, first create a 5x5 matrix with first the keyword and then followed by the rest of the letters of the alphabet, while omitting any
later repeats in the phrase. Then use these three rules to encode the plaintext:

\begin{center}
 \begin{tabular}{|c|c|} 
 \hline
 different rows and columns & \rightleftharpoons \\
 \hline
 only same row & \rightarrow \rightarrow  \\
 \hline
 only same col & \Downarrow \\ & \Downarrow  \\
 \hline
 \end{tabular}
\end{center}
If two of the same letters occur consecutively, add a space character such as X or Z. Loop to the begining or end if at edges.
*** Decoding with Cribs
It's a shaft. Have fun!
** Railfence Cipher
*** Encoding
Write the text in three rows like a railfence. Then copy each row, which will create your ciphered text.
\begin{equation}
\begin{bmatrix}
    T & _ & _ & _ & C & _ & _ & _ & E & _ &\\
    _ & H & _ & S & _ & I & _ & H & _ & R &\\
    _ & _ & I & _ & _ & _ & P & _ & _ & _ &\\
\end{bmatrix}
\end{equation}
Encoded: TCEHSIHRIP
*** Decoding
To decode, round, divide the length of the ciphered text by 2 and ignore any remainders. This will be the length 
of the 2nd row, and the first and third row will be half of it. Then copy it down accordingly to create the fence, which can be rewritten
as the plaintext.
* ADFGVX Cipher and Vigenere Cipher
** ADFGVX Cipher
*** Encoding
To encode, put it through a ADFGVX which is formatted like this:
// //
and find the row and column letter corresponding to it, which will be A, D, F, G, V, or X. Then encode this with Keyword Columnar Transform, which will result in the encoded message.
*** Decoding
First part to decoding is to decode the Keyword Columnar Transform. 
Then find the letter corresponding to every two consecutive letters which will be its row and column. To this process over the
entire ciphertext and then you are done.
** Vigenere Cipher
*** Encoding
To encode, either attain or make a keyword. Then find the index of each letter of the plaintext and the keyword and the sum of the two mod 26 will
result in your ciphered letter.
*** Decoding
To decode, attain  keyword. Then find the index of each letter of the ciphertext and the keyword and the difference between the two will
result in your plaintext letter. 
*** Friedman Test
*** Kasiki Test
**** Find the most common trigraphs in the ciphertext and the difference between them
**** The GCD of all the differences is the length of the keyword.
*** Steps to Decrypt
**** Use Friedman and Kasiki Test to attain length of your keyword $n$.
**** Split your ciphertext in to $n$ cosets.
**** For each coset, compare their relative frequencies in the cosets to their relative frequencies in the coset. The one's with smallest differences between the two are likely to be the letters for the keyword.
**** Based on this form your keyword and then decode.

